# .github/workflows/build-macos.yml
name: Build macOS Binary

on:
  push:
    tags:
      - "v*" # only run on version tags like v1.0.0
  workflow_dispatch:

jobs:
  build-macos:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build binary
        run: |
          pyinstaller --onefile scripts/main.py -n dhis2-tool

      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
          name: dhis2-tool-macos
          path: dist/dhis2-tool
